# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Xiao Nan
tagline:          'Machine Learning, PyTorch, Keras, Blogging, Tweets'
url:              http://www.xiaonan.co
shorturl:         xiaonan.co

author:
  name:           'Xiao Nan'
  url:            https://twitter.com/xia0nan

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/shawn-nx/shawn-nx.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
